export default {
	CLICK_QUERY: 'CLICK_QUERY',
	CLICK_ACCEPT: 'CLICK_ACCEPT',
	CLICK_CANCEL: 'CLICK_CANCEL',
	HTTP_STATUS_200: 'HTTP_STATUS_200',
	HTTP_STATUS_500: 'HTTP_STATUS_500',
	LOADING: 'LOADING'
}
